version: '3.8'

services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:80"
    depends_on:
      - db
    environment:
      - ConnectionStrings__DefaultConnection=Server=db;Database=ConcordCloud;User=sa;Password=YourStrongPassword!;TrustServerCertificate=True;
      - AzureBlobStorage__ConnectionString=YourAzureBlobStorageConnectionString
      - JWT__Secret=YourJwtSecretKey
      - JWT__Issuer=ConcordCloud
      - JWT__Audience=ConcordCloudUsers
      - JWT__ExpiryInDays=7

  web:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "80:80"
    depends_on:
      - api

  db:
    image: mcr.microsoft.com/mssql/server:2019-latest
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=YourStrongPassword!
    ports:
      - "1433:1433"
    volumes:
      - sqldata:/var/opt/mssql

volumes:
  sqldata:
